apiVersion: v1
kind: ReplicationController
metadata:
  name: anuglarmeetup
spec:
  replicas: 1
  selector:
    app: anuglarmeetup
    vesion : 0.0.1
  template:
    metadata:
      labels:
        app: anuglarmeetup
        vesion : 0.0.1
    spec:
      containers:
        - name: anuglarmeetup
          image: gcr.io/clean-silo-630/github-tonmanna-angular_meetup_pipeline:4be984e3080187cedb63c6b412f70112208e83df
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: dev
              value: "true"
      imagePullSecrets:
        - name: gcrpull